-- NEW TABLE
CREATE TABLE language
(
	ID varchar(3) not null,
	NAME varchar(500) not null,

	PRIMARY KEY (ID)
);

CREATE TABLE movie_title
(
	MOVIE_ID int not null,
	LANGUAGE_ID varchar(3) not null,
	TITLE varchar(500) not null,

	PRIMARY KEY (MOVIE_ID, LANGUAGE_ID),
	FOREIGN KEY FK_MA_MOVIE (MOVIE_ID)
		REFERENCES movie(ID)
		ON UPDATE RESTRICT
		ON DELETE RESTRICT,
	FOREIGN KEY FK_MA_LANGUAGE (LANGUAGE_ID)
		REFERENCES language(ID)
		ON UPDATE RESTRICT
		ON DELETE RESTRICT
);

-- FILL LANGUAGE TABLE
INSERT INTO language (ID, NAME)
VALUES ('ru', 'Russian'),
       ('en', 'English')

-- COPY RU MOVIE IN LANGUAGE TABLE
INSERT INTO movie_title (MOVIE_ID, LANGUAGE_ID, TITLE)
SELECT ID, 'ru', TITLE FROM movie

-- DELETE COLUMN TITLE FROM MOVIE TABLE
ALTER TABLE movie DROP COLUMN TITLE;